spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test-workflow
    username: postgres
    password: imdw1A96
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      log:
        sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
